adapter:
  build: .
  volumes:
   - .:/usr/src/app
  links:
   - mysql
  environment:
   - NODE_ENV=test

mysql:
  image: mysql
  environment:
   - MYSQL_DATABASE=offshoreSql
   - MYSQL_USER=offshore
   - MYSQL_PASSWORD=offshore
   - MYSQL_ROOT_PASSWORD=offshore
